### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by MarcelloTheArcane** [motia/nuxt-auth-refresh#1]
Please could you add some instructions for how to install this module?

- Is there an NPM package?
- What is `~/modules/refresh-auth`, and where is it from? Is it a config file I have to create?

**Comment by motia** [comment]
Hi @MarcelloTheArcane, 
- @haosx86 published a fork of this repository as [package](https://www.npmjs.com/package/nuxt-auth-refresh).
You can install it using yarn:
`yarn add nuxt-auth-refresh`
Then you have to add  `nuxt-refresh-auth` to the modules entry inside `nuxt.config.js`

- `~` stands for the src dir of your nuxt app (defaults to the its root). You can download the repository into a directory `~/modules/refresh-auth`.
Then add  `~/modules/refresh-auth` to your the `modules` property inside `nuxt.config.js`

Sorrry for the late response for some reason I did not get an email for your issue.

**Comment by MarcelloTheArcane** [comment]
Aha, that makes sense. Thanks!
