### ISSUE TITLE
$authRefresh is undefined

### ISSUE THREAD

**Issue by bradley-varol** [motia/nuxt-auth-refresh#12]
I've copied the `refresh-auth-token.js` plugin from the README and this doesn't work as $authRefresh is undefined inside the plugin.

nuxt 2.14.0 with@nuxtjs/auth 4.9.1.

```js
modules: [
    'nuxt-auth-refresh',
    '@nuxtjs/auth',
    '@nuxtjs/axios',
],
auth: {
    plugins: [
        '~/plugins/refresh-auth-token', // prevents "$auth is undefined"
    ],
    strategies: {
        // ...
    },
},
```

**Comment by motia** [comment]
Yes, the plugin should be added to `auth.plugins` and not `plugins` as you noted.
I will update the docs.

Thanks.

**Comment by bradley-varol** [comment]
I've added the plugin to `auth.plugins` and `app.$auth` is defined but `app.$authRefresh` is undefined.

**Comment by motia** [comment]
Please use `@motia/nuxt-auth-refresh` instead of `nuxt-auth-refresh`. The latter is not linked to this repository and is out of date.
Also, I added a couple of tweaks to the  README to improve the integration.

Good luck

**Comment by bradley-varol** [comment]
Thank you, that is now working!
